# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Employee.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Data_Entry(object):
    def setupUi(self, Data_Entry):
        Data_Entry.setObjectName("Data_Entry")
        Data_Entry.resize(800, 600)
        Data_Entry.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.centralwidget = QtWidgets.QWidget(Data_Entry)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 30, 801, 511))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Name_lbl = QtWidgets.QLabel(self.frame)
        self.Name_lbl.setGeometry(QtCore.QRect(60, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.Name_lbl.setFont(font)
        self.Name_lbl.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.Name_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Name_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_lbl.setObjectName("Name_lbl")
        self.Dept_lbl = QtWidgets.QLabel(self.frame)
        self.Dept_lbl.setGeometry(QtCore.QRect(60, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.Dept_lbl.setFont(font)
        self.Dept_lbl.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.Dept_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Dept_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Dept_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Dept_lbl.setObjectName("Dept_lbl")
        self.ID_lbl = QtWidgets.QLabel(self.frame)
        self.ID_lbl.setGeometry(QtCore.QRect(60, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.ID_lbl.setFont(font)
        self.ID_lbl.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.ID_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ID_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ID_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ID_lbl.setObjectName("ID_lbl")
        self.Phone_lbl = QtWidgets.QLabel(self.frame)
        self.Phone_lbl.setGeometry(QtCore.QRect(60, 320, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.Phone_lbl.setFont(font)
        self.Phone_lbl.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.Phone_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Phone_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Phone_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Phone_lbl.setObjectName("Phone_lbl")
        self.Des_lbl = QtWidgets.QLabel(self.frame)
        self.Des_lbl.setGeometry(QtCore.QRect(60, 390, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.Des_lbl.setFont(font)
        self.Des_lbl.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.Des_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Des_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Des_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Des_lbl.setObjectName("Des_lbl")
        self.Name_le = QtWidgets.QLineEdit(self.frame)
        self.Name_le.setGeometry(QtCore.QRect(312, 50, 441, 31))
        self.Name_le.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.Name_le.setObjectName("Name_le")
        self.Dept_le = QtWidgets.QLineEdit(self.frame)
        self.Dept_le.setGeometry(QtCore.QRect(310, 130, 441, 31))
        self.Dept_le.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.Dept_le.setObjectName("Dept_le")
        self.ID_le = QtWidgets.QLineEdit(self.frame)
        self.ID_le.setGeometry(QtCore.QRect(310, 220, 441, 31))
        self.ID_le.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.ID_le.setObjectName("ID_le")
        self.Phone_le = QtWidgets.QLineEdit(self.frame)
        self.Phone_le.setGeometry(QtCore.QRect(310, 310, 441, 31))
        self.Phone_le.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.Phone_le.setObjectName("Phone_le")
        self.Des_le = QtWidgets.QLineEdit(self.frame)
        self.Des_le.setGeometry(QtCore.QRect(310, 380, 441, 31))
        self.Des_le.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.Des_le.setObjectName("Des_le")
        self.Clear_pb = QtWidgets.QPushButton(self.frame)
        self.Clear_pb.setGeometry(QtCore.QRect(180, 470, 93, 28))
        self.Clear_pb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Clear_pb.setAutoDefault(False)
        self.Clear_pb.setDefault(True)
        self.Clear_pb.setFlat(True)
        self.Clear_pb.setObjectName("Clear_pb")
        self.Submit_pb = QtWidgets.QPushButton(self.frame)
        self.Submit_pb.setGeometry(QtCore.QRect(520, 470, 93, 28))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Submit_pb.setFont(font)
        self.Submit_pb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Submit_pb.setAutoDefault(False)
        self.Submit_pb.setDefault(True)
        self.Submit_pb.setFlat(True)
        self.Submit_pb.setObjectName("Submit_pb")
        Data_Entry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Data_Entry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Data_Entry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Data_Entry)
        self.statusbar.setObjectName("statusbar")
        Data_Entry.setStatusBar(self.statusbar)

        self.retranslateUi(Data_Entry)
        QtCore.QMetaObject.connectSlotsByName(Data_Entry)

    def retranslateUi(self, Data_Entry):
        _translate = QtCore.QCoreApplication.translate
        Data_Entry.setWindowTitle(_translate("Data_Entry", "MainWindow"))
        self.Name_lbl.setText(_translate("Data_Entry", "Name"))
        self.Dept_lbl.setText(_translate("Data_Entry", "Department"))
        self.ID_lbl.setText(_translate("Data_Entry", "ID"))
        self.Phone_lbl.setText(_translate("Data_Entry", "Phone Number"))
        self.Des_lbl.setText(_translate("Data_Entry", "Designation"))
        self.Clear_pb.setText(_translate("Data_Entry", "Clear Fields"))
        self.Submit_pb.setText(_translate("Data_Entry", "Submit"))

