# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search_Data.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Search_Data(object):
    def setupUi(self, Search_Data):
        Search_Data.setObjectName("Search_Data")
        Search_Data.resize(400, 600)
        Search_Data.setMinimumSize(QtCore.QSize(400, 600))
        Search_Data.setMaximumSize(QtCore.QSize(400, 600))
        Search_Data.setStyleSheet("background-color: rgb(201, 251, 255);")
        self.centralwidget = QtWidgets.QWidget(Search_Data)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 50, 401, 471))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.idlbl = QtWidgets.QLabel(self.frame)
        self.idlbl.setGeometry(QtCore.QRect(14, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idlbl.setFont(font)
        self.idlbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.idlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.idlbl.setObjectName("idlbl")
        self.idle = QtWidgets.QLineEdit(self.frame)
        self.idle.setGeometry(QtCore.QRect(110, 61, 161, 31))
        self.idle.setObjectName("idle")
        self.Search = QtWidgets.QPushButton(self.frame)
        self.Search.setGeometry(QtCore.QRect(290, 60, 93, 31))
        self.Search.setDefault(True)
        self.Search.setFlat(True)
        self.Search.setObjectName("Search")
        self.idlbl_2 = QtWidgets.QLabel(self.frame)
        self.idlbl_2.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idlbl_2.setFont(font)
        self.idlbl_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.idlbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.idlbl_2.setObjectName("idlbl_2")
        self.idlbl_3 = QtWidgets.QLabel(self.frame)
        self.idlbl_3.setGeometry(QtCore.QRect(10, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idlbl_3.setFont(font)
        self.idlbl_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.idlbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.idlbl_3.setObjectName("idlbl_3")
        self.idlbl_4 = QtWidgets.QLabel(self.frame)
        self.idlbl_4.setGeometry(QtCore.QRect(10, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idlbl_4.setFont(font)
        self.idlbl_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.idlbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.idlbl_4.setObjectName("idlbl_4")
        self.idlbl_5 = QtWidgets.QLabel(self.frame)
        self.idlbl_5.setGeometry(QtCore.QRect(10, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idlbl_5.setFont(font)
        self.idlbl_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.idlbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.idlbl_5.setObjectName("idlbl_5")
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setGeometry(QtCore.QRect(170, 180, 211, 22))
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.dept = QtWidgets.QLineEdit(self.frame)
        self.dept.setGeometry(QtCore.QRect(170, 250, 211, 22))
        self.dept.setReadOnly(True)
        self.dept.setObjectName("dept")
        self.phone = QtWidgets.QLineEdit(self.frame)
        self.phone.setGeometry(QtCore.QRect(170, 330, 211, 22))
        self.phone.setReadOnly(True)
        self.phone.setObjectName("phone")
        self.designation = QtWidgets.QLineEdit(self.frame)
        self.designation.setGeometry(QtCore.QRect(170, 410, 211, 22))
        self.designation.setReadOnly(True)
        self.designation.setObjectName("designation")
        Search_Data.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Search_Data)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        Search_Data.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Search_Data)
        self.statusbar.setObjectName("statusbar")
        Search_Data.setStatusBar(self.statusbar)

        self.retranslateUi(Search_Data)
        QtCore.QMetaObject.connectSlotsByName(Search_Data)

    def retranslateUi(self, Search_Data):
        _translate = QtCore.QCoreApplication.translate
        Search_Data.setWindowTitle(_translate("Search_Data", "MainWindow"))
        self.idlbl.setText(_translate("Search_Data", "ID"))
        self.Search.setText(_translate("Search_Data", "Search"))
        self.idlbl_2.setText(_translate("Search_Data", "Name"))
        self.idlbl_3.setText(_translate("Search_Data", "Deptartment"))
        self.idlbl_4.setText(_translate("Search_Data", "Phone"))
        self.idlbl_5.setText(_translate("Search_Data", "Designation"))

